### ISSUE TITLE
NPE при вводе места жительства

### ISSUE THREAD

**Issue by vochupin** [vochupin/uazbot#2]
толи без аргументов толи еще что. В чате не нашел ничего криминального:

uazbot, [01.01.21 21:22]
Запись по персоне создана(изменена): 
Имя: ************
Фамилия: ************
username: ************
Откуда(как сам ввел): 
Откуда(из OSM): null
Координаты места из OSM:
Долгота: ...
Широта: ...

************ ************, [01.01.21 21:23]
/from@uazchatbot Магнитогорск

uazbot, [01.01.21 21:23]
Запись по персоне создана(изменена): 
Имя: ************
Фамилия: ************
username: ************
Откуда(как сам ввел): 
Откуда(из OSM): null
Координаты места из OSM:
Долгота: ...
Широта: ...

2021-01-01 21:23:53.887  WARN 79030 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Execution of JMS message listener failed, and no ErrorHandler has been set.

org.springframework.jms.listener.adapter.ListenerExecutionFailedException: Listener method 'public void com.uazbot.service.MessageReciever.analyzeForUpdateType(org.telegram.telegrambots.meta.api.objects.Update)' threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:122) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NullPointerException: null
	at com.uazbot.service.MessageReciever.analyzeForUpdateType(MessageReciever.java:44) ~[classes!/:1.0-SNAPSHOT]
	at jdk.internal.reflect.GeneratedMethodAccessor189.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:114) ~[spring-jms-5.2.8.RELEASE.jar!/:5.2.8.RELEASE]
	... 10 common frames omitted

**Comment by vochupin** [comment]
при редактировании ранее введенной команды - Message присылается = null
отредактированное сообщение надо забрать из поля editedMessage #6
